on: [push]
name: BC
jobs:
  roave_bc_check:
    name: Roave BC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga